version: '3'
services:
  backend:
    image: registry.emontazysta.pl/admin/test-backend:latest
    container_name: backend
    networks:
      - utils_utils
      
networks:
  utils_utils:
    external: true
