name: Deploy to Portainer

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.emontazysta.pl
          repository: admin/test-backend
          tag: latest
      - name: Create stack in Portainer
        uses: carlrygart/portainer-stack-deploy@v1.3.0
        with:
          stack-definition: Java/.build/stack-file.yaml
          portainer-host: ${{ secrets.PORTAINER_URL }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack_name: production
