Certainly! Here is an example of a complete GitHub Actions workflow that builds and pushes a Spring Boot application to a private Docker registry using a multi-stage Docker image, and then deploys the application to Portainer using the lscr.io/linuxserver/portainer-actions action:

  Copy code
name: Deploy to Portainer

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.emontazysta.pl
          repository: admin/test-backend
          tag: latest
      - name: Create stack in Portainer
        uses: lscr.io/linuxserver/portainer-actions@master
        with:
          portainer_url: ${{ secrets.PORTAINER_URL }}
          portainer_username: ${{ secrets.PORTAINER_USERNAME }}
          portainer_password: ${{ secrets.PORTAINER_PASSWORD }}
          stack_name: production
          stack_file: |
            $(cat .build/stack-file.yml)
          merge_mode: merge